
[functions.dua-autonomous]
enabled = true
# Allow calling this Edge Function without a JWT (mobile app uses public URL)
verify_jwt = false
import_map = "./functions/dua-autonomous/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dua-autonomous/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dua-autonomous/*.html" ]

[functions.dua-client]
enabled = true
verify_jwt = false
import_map = "./functions/dua-client/deno.json"
entrypoint = "./functions/dua-client/index.ts"

[functions.dua-admin]
enabled = true
verify_jwt = false
import_map = "./functions/dua-admin/deno.json"
entrypoint = "./functions/dua-admin/index.ts"
